version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Docker-files/node/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - agent
    environment:
      - NODE_ENV=production

  agent:
    build:
      context: .
      dockerfile: Docker-files/python/Dockerfile
    ports:
      - "8000:8000"

