version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Docker-files/node/Dockerfile
    ports:
      - "5000:5001"
    depends_on:
      - agent
    env_file:
      - Backend/.env

  agent:
    build:
      context: .
      dockerfile: Docker-files/python/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - agent/.env